### ISSUE TITLE
Dependency on Log::Report

### ISSUE THREAD

**Issue by epa** [markov2/perl5-Hash-Case#1]
Hi, I know that with version 1.01 the Hash::Case module was converted to use Log::Report for error handling.  I do agree with reusing code and that Log::Report can improve error handling.  However it pulls in a lot of dependencies:

Dancer2
Log::Dispatch
Log::Log4perl
Mojolicious
Moo
Plack::Test

and possibly transitive dependencies of those.  That's a lot of stuff just to implement a case-insensitive hash!  If you're using the CPAN shell to install directly, or on a broad-based Linux distribution like Fedora or Debian, you can probably pull down all these packages and only lose a bit of disk space.  But other platforms like enterprise Linux distributions will tend not to package all of these frameworks, although they do provide a recent Perl and many of the most popular modules.

Would you consider cutting the dependency on Log::Report so that the code for Hash::Case becomes once again 'too simple to be true' as it was described back on 2002?  That in turn will make it more likely to be included as standard in Linux distributions (or Perl distributions) which want to ship useful modules but not necessarily the whole of Dancer2, Mojolicious etc.

**Comment by markov2** [comment]
* Ed Avis (notifications@github.com) [200206 11:18]:
> Hi, I know that with version 1.01 the Hash::Case module was converted
> to use Log::Report for error handling.

Well, yes, back in 2010.

> I do agree with reusing code
> and that Log::Report can improve error handling.  However it pulls in
> a lot of dependencies:
> 
> Dancer2
> Log::Dispatch
> Log::Log4perl
> Mojolicious
> Moo
> Plack::Test

There is no (official) dependency on Dancer2.  It is 'use'd in one of the
components, but on purpose not in the Makefile.PL dependency list.

[...]
> But other platforms like enterprise Linux distributions will tend not
> to package all of these frameworks, although they do provide a recent
> Perl and many of the most popular modules.

Log::Report is packaged by some distributions because close to all my
modules do use it (like XML::Compile(::SOAP))

> Would you consider cutting the dependency on Log::Report so that the
> code for Hash::Case becomes once again 'too simple to be true' as it
> was described back on 2002?

I am not unwilling to change it back, even though the situation is not
as bad as you suggest.  Other people's mistakes make it look as bad as
you list here.

> That in turn will make it more likely to be
> included as standard in Linux distributions (or Perl distributions) which
> want to ship useful modules but not necessarily the whole of Dancer2,
> Mojolicious etc.

Well, I have not had a reaction on this module since 2012, when Florian
found a typo when packaging it for Debian.  Should I care to have this
packaged?
-- 
Regards,
               MarkOv

------------------------------------------------------------------------
       Mark Overmeer MSc                                MARKOV Solutions
       Mark@Overmeer.net                          solutions@overmeer.net
http://Mark.Overmeer.net                   http://solutions.overmeer.net

**Comment by epa** [comment]
Ah, so the generation of an RPM spec file (as used by Fedora, at least) is arguably too strict in finding a dependency on Dancer2.

**Comment by markov2** [comment]
Maybe it does not run 'perl Makefile.PL' and then check-out the dependencies as found in the generated Makefile.  Probably they go on hunt for packages directly from the pm files.

If you use Hash::Case, I will make this change for you.  Otherwise, I don't care.

**Comment by epa** [comment]
Yes, I use Hash::Case and am currently packaging it for RHEL (internally) using the Fedora package as a starting point.

Case-insensitive hash lookups seem like such a basic thing I'm surprised the module is not part of core perl.  Maybe in the traditional Unix world there isn't much call for them, but if you deal with Windows systems, SQL databases and so on...

**Comment by epa** [comment]
P.S. for the time being I have dodged the dependency by packaging the older version 1.006.

**Comment by markov2** [comment]
Replaces Log::Report::error by croak().  Released 1.04

**Comment by markov2** [comment]
* Ed Avis (notifications@github.com) [200206 14:46]:
> P.S. for the time being I have dodged the dependency by packaging
> the older version 1.006.

Replaced Log::Report::error() by croak()   Released as 1.04

The regression tests do not complain, that's all I can say about it.
-- 
greetz,

               MarkOv

------------------------------------------------------------------------
drs Mark A.C.J. Overmeer                                MARKOV Solutions
       Mark@Overmeer.net                          solutions@overmeer.net
http://Mark.Overmeer.net                   http://solutions.overmeer.net

**Comment by epa** [comment]
Thanks!  Let me scurry off and build an RPM package of it.

**Comment by epa** [comment]
Hmm, I think the test suite does complain:
`t/30pres1.t .. Can't locate Log/Report.pm in @INC `
I still see Log::Report used in Hash/Case/Preserve.pm.

**Comment by epa** [comment]
I think just removing the `use Log::Report` line is enough to fix it.

**Comment by markov2** [comment]
* Ed Avis (notifications@github.com) [200206 15:37]:
> I think just removing the `use Log::Report` line is enough to fix it.

I tried to be careful, but failed.  I'll immediately release 1.05,
otherwise get spammed by cpantesters ;-)
-- 
               MarkOv

------------------------------------------------------------------------
drs Mark A.C.J. Overmeer                                MARKOV Solutions
       Mark@Overmeer.net                          solutions@overmeer.net
http://Mark.Overmeer.net                   http://solutions.overmeer.net

**Comment by epa** [comment]
Looks good, thanks.
